apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:k+8fkyJdd8SQKgJTQvfjD3u1uEBwoWGAvQ==,iv:bCBLu0xPR/6lvXi4ZJ9fOMLoQJg+liLVN6W7hN3aY58=,tag:Zf8EnRzAm/4NyWeEtqO1/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-27T14:47:17Z"
    mac: ENC[AES256_GCM,data:Z6ZS045ns9XvAZO1ZhE1DsWt+VAwso9tgkVb/bGsi3kaII92xC3xB228DRsdQUw4F1DkAunPCu2UBGZ8dZSMLA0NfTwF7/e0mjJDZGPog12hlU6ALUSDpHxDd7AB3t1DYX0e3B9k/i9ahh1DM6V0R341IXsN2nAlxrkkfP1JuU8=,iv:jDY1Hnp2w7K/1hKoI3Yg09J620+4Z0HOJZbRrIgE9DI=,tag:kwalx9C8wd28yy+b8CqAkA==,type:str]
    pgp:
        - created_at: "2026-02-27T14:47:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2yBtjozwuJoAQv/aAj/EtV4JcAhq+y8F1TmH6UM5EPKkBvSLhUb1dTJQv0w
            iiXkQPMFt0slaS8mSCjAf5HC3nb0NpzVQpzQPccWhVGKvWC2PzSobpSiHHkrorhu
            Lbuuu4cIgoikLe8UofA/buwnzIi8hA0lqhAC0eMFgSjD0Vv8PJqze95vErm+o+OL
            gHdfP8aeuu47bU0s1O/1Qi5kVWv96cIcN3j2MPAX9GYphuLIURcK09LYyLZqFwyi
            f8oTHza2bBQxjwWzhjZAyY7nXUz+jgfh69x7K9i84vMIlYex/LdVhmMdQGkNXr7p
            +umqAPBokAJj8sGzOAjzQgSFrKM3kWL03zP0tQWPQjl6IgpKeUNHGBtcidQXEchV
            XIwaIOJkEfV1O7gcipMTyynGalKtK7ExiAly+AmZHSATMJCDJl4f8j1Gm9zPkVYE
            a0hCTuq2L5OObTZhrHy42vtfWi939lRX7EE4ap4vDSPC65jawIIe/6QDW0RQhznC
            V1eA8E+7dm5wWe0zEnaz1GgBCQIQOdj3PDTt8yEAExfIVP3ytCYCBB9FysAGUVYb
            GCPbraXLf6g3FHR5o78bEC0Nlx8G4chvLXKgFdZxJrctT8G1rZUtXknGRF8XJBoT
            m8xz3e/Umi2axFdPHBcCalDx6UHw0ymjDw==
            =QLHs
            -----END PGP MESSAGE-----
          fp: 4B82E139120CEB37CA4B8347BC2BA0756BBE2CB0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
